Add support for Rack 3.X
This requires using request.params instead of accessing the parameters
directly via []. See https://github.com/omniauth/omniauth/issues/1135

Fixes "undefined method `[]' for an instance of Rack::Request: NoMethodError"